FROM golang:1.13-alpine3.10 AS builder

RUN apk --update --no-cache add ca-certificates

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
#RUN go build -a -installsuffix cgo -o main .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags static_all -o main ./servicea/main.go

RUN ls -lah
FROM scratch
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8080
ENTRYPOINT ["./main"]